services:
  microservices-api:
    image: microservices-api:latest
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./certs:/certs:ro
    environment:
      - PORT=8080
      - PROD=false
      - KEYS=test-1111,test-2222
      - OPEN=/livez,/readyz,/healthz,/metrics
      # ---
      # - TLS_CERT=/certs/cert.pem
      # - TLS_KEY=/certs/key.pem
      # ---
      - HIST_ADDR=history:50051
      - CURR_ADDR=currency:50052
      - CONV_ADDR=conversion:50053
      # ---
      - HIST_TOUT=5s
      - CURR_TOUT=5s
      - CONV_TOUT=5s
      # ---
      - READ_TOUT=10s
      - IDLE_TOUT=15s
      - WRITE_TOUT=20s
      - SHUTDOWN_TOUT=25s
      # ---
      - RATE_LIMIT=5
      - RATE_BURST=10
      - RATES_LIMIT=5
      - RATES_BURST=10
      - CONVERT_LIMIT=5
      - CONVERT_BURST=10
    healthcheck:
      test: ["CMD-SHELL", "wget --no-check-certificate --spider --quiet https://localhost:8080/healthz || exit 1"]
      retries: 3
      timeout: 3s
      interval: 3s
      start_period: 3s

    restart: unless-stopped
    mem_reservation: 256m
    mem_limit: 512m
    cpus: '0.5'

    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_NAME: ${CMD_NAME:-microservices-api}
        GO_VERSION: ${GO_VERSION:-1.25.0}
    container_name: microservices-api





